name: Apply
on:
  push:
    branches:
      - main # Triggers on pushes to the 'main' branch
  workflow_dispatch: # triggers manual workflow
jobs:
  build:
    runs-on: self-hosted # Specifies the runner environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Checks out the repository code

      - name: terraform apply
        env:
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
        run: make dev-plan token=$VAULT_TOKEN
          # Example: Install Node.js dependencies

      - name: Run tests
        run: echo 'running tests' # Example: Run tests